import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome' });
const p = await (await b.newContext({ serviceWorkers: 'block', locale: 'pl-PL' })).newPage();
const net = [];
p.on('response', r => { if (r.url().includes('leaflet') || r.status() >= 400) net.push(r.status() + ' ' + r.url().slice(0, 110)); });
p.on('pageerror', e => console.log('PAGEERROR', e.message));
await p.goto('https://3dfile.link/zamow', { waitUntil: 'networkidle', timeout: 90000 });
console.log('window.L =', await p.evaluate(() => typeof window.L));
await p.evaluate(() => { const s = document.getElementById('fShipping'); s.value = 'standard'; toggleShipUI(); });
await p.waitForFunction(() => document.querySelectorAll('#paczkomatList .pczrow').length > 0, null, { timeout: 60000 });
await p.waitForTimeout(3000);
console.log('po render: window.L =', await p.evaluate(() => typeof window.L));
console.log('#pczMap display =', await p.evaluate(() => { const e = document.getElementById('pczMap'); return e ? getComputedStyle(e).display : 'BRAK ELEMENTU'; }));
console.log('#pczMap innerHTML dlugosc =', await p.evaluate(() => document.getElementById('pczMap').innerHTML.length));
console.log('PCZ_MAP != null =', await p.evaluate(() => typeof PCZ_MAP !== 'undefined' ? String(PCZ_MAP) : 'undef'));
console.log('drawPczMap istnieje =', await p.evaluate(() => typeof drawPczMap));
console.log('L.map =', await p.evaluate(() => typeof window.L !== 'undefined' && window.L ? typeof window.L.map : 'brak'));
console.log('--- net ---'); net.slice(0, 10).forEach(x => console.log('  ' + x));
await b.close();
